# Service to dynamically add new waypoint

std_msgs/Header request_header

rosplane_msgs/State state

rosplane_msgs/ControllerCommands controller_commands
---
std_msgs/Header response_header

rosflight_msgs/Command command

rosplane_msgs/State commanded_state
